name: Shutter Debug
markdown: redcarpet
pygments: true
excerpt_separator: <!--excerpt-->

my_name: Anthony Chuang
my_facebook: http://www.facebook.com/ChuangPhotos
my_flickr: http://www.flickr.com/photos/anthony_chuang/
my_email: anthony AT shutterdebug.com